apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: waarp-cifs
  name: waarp-cifs
spec:
  ports:
  - name: "137"
    port: 137
    targetPort: 137
  - name: "137"
    port: 137
    protocol: UDP
    targetPort: 137
  - name: "138"
    port: 138
    targetPort: 138
  - name: "138"
    port: 138
    protocol: UDP
    targetPort: 138
  - name: "139"
    port: 139
    targetPort: 139
  - name: "445"
    port: 445
    targetPort: 445
  - name: "445"
    port: 445
    protocol: UDP
    targetPort: 445
  selector:
    io.kompose.service: waarp-cifs
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: waarp-cifs
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: waarp-cifs
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: "5"
        - name: TZ
          value: Europe/Paris
        - name: WORKGROUP
          value: EXAMPLE
        - name: AD_PASSWORD
          value: Dj43l1ss.01
        - name: AD_USERNAME
          value: fjudith
        - name: ADMIN_SERVER
          value: dc1.example.com dc2.example.com
        - name: DOMAIN_NAME
          value: example.com
        image: fjudith/samba-join-ad
        name: waarp-cifs
        ports:
        - containerPort: 137
        - containerPort: 137
          protocol: UDP
        - containerPort: 138
        - containerPort: 138
          protocol: UDP
        - containerPort: 139
        - containerPort: 445
        - containerPort: 445
          protocol: UDP
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
